// Mocks generated by Mockito 5.4.2 from annotations
// in video_game_completed/test/features/search/cubits/search_video_game_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:video_game_completed/core/domain/entities/result.dart' as _i2;
import 'package:video_game_completed/core/enums/search_filter_enums.dart'
    as _i6;
import 'package:video_game_completed/core/enums/video_game_status.dart' as _i9;
import 'package:video_game_completed/features/common/domain/entities/video_game_db.dart'
    as _i8;
import 'package:video_game_completed/features/common/domain/repositories/video_games_repository.dart'
    as _i3;
import 'package:video_game_completed/features/details/data/models/video_game_model_with_indiv.dart'
    as _i7;
import 'package:video_game_completed/features/search/data/models/search_videogame_response.dart'
    as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResult_0<T> extends _i1.SmartFake implements _i2.Result<T> {
  _FakeResult_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [VideoGamesRepository].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockVideoGamesRepository extends _i1.Mock
    implements _i3.VideoGamesRepository {
  MockVideoGamesRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Result<_i5.SearchVideogameResponse>> searchVideoGame(
    int? pageResult,
    String? searchText,
    _i6.SearchFilterSortBy? sortBy,
    _i6.SearchFilterPlatform? platform,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchVideoGame,
          [
            pageResult,
            searchText,
            sortBy,
            platform,
          ],
        ),
        returnValue: _i4.Future<_i2.Result<_i5.SearchVideogameResponse>>.value(
            _FakeResult_0<_i5.SearchVideogameResponse>(
          this,
          Invocation.method(
            #searchVideoGame,
            [
              pageResult,
              searchText,
              sortBy,
              platform,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i5.SearchVideogameResponse>>);
  @override
  _i4.Future<_i2.Result<_i7.VideoGameWithIndivModel>> getVideoGameDetails(
          int? remoteId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVideoGameDetails,
          [remoteId],
        ),
        returnValue: _i4.Future<_i2.Result<_i7.VideoGameWithIndivModel>>.value(
            _FakeResult_0<_i7.VideoGameWithIndivModel>(
          this,
          Invocation.method(
            #getVideoGameDetails,
            [remoteId],
          ),
        )),
      ) as _i4.Future<_i2.Result<_i7.VideoGameWithIndivModel>>);
  @override
  _i4.Future<_i2.Result<List<_i8.VideoGameDb>>> getLocalVideoGames() =>
      (super.noSuchMethod(
        Invocation.method(
          #getLocalVideoGames,
          [],
        ),
        returnValue: _i4.Future<_i2.Result<List<_i8.VideoGameDb>>>.value(
            _FakeResult_0<List<_i8.VideoGameDb>>(
          this,
          Invocation.method(
            #getLocalVideoGames,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Result<List<_i8.VideoGameDb>>>);
  @override
  _i4.Future<_i2.Result<void>> insertLocalVideoGame(
    int? remoteId,
    String? gameName,
    String? imageName,
    int? releaseYear,
    String? platformSelected,
    _i9.VideoGameStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertLocalVideoGame,
          [
            remoteId,
            gameName,
            imageName,
            releaseYear,
            platformSelected,
            status,
          ],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #insertLocalVideoGame,
            [
              remoteId,
              gameName,
              imageName,
              releaseYear,
              platformSelected,
              status,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);
  @override
  _i4.Future<_i2.Result<void>> deleteLocalVideoGames(int? remoteId) =>
      (super.noSuchMethod(
        Invocation.method(
          #deleteLocalVideoGames,
          [remoteId],
        ),
        returnValue: _i4.Future<_i2.Result<void>>.value(_FakeResult_0<void>(
          this,
          Invocation.method(
            #deleteLocalVideoGames,
            [remoteId],
          ),
        )),
      ) as _i4.Future<_i2.Result<void>>);
}
