// Mocks generated by Mockito 5.4.2 from annotations
// in video_game_completed/test/features/common/data/repositories/video_games_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:mockito/mockito.dart' as _i1;
import 'package:video_game_completed/core/data/database_provider.dart' as _i4;
import 'package:video_game_completed/core/enums/search_filter_enums.dart'
    as _i7;
import 'package:video_game_completed/core/enums/video_game_status.dart' as _i10;
import 'package:video_game_completed/features/common/data/datasources/video_game_local_data_source.dart'
    as _i8;
import 'package:video_game_completed/features/common/domain/datasources/how_long_beat_data_source.dart'
    as _i5;
import 'package:video_game_completed/features/common/domain/entities/video_game_db.dart'
    as _i9;
import 'package:video_game_completed/features/details/data/models/video_game_model_with_indiv.dart'
    as _i3;
import 'package:video_game_completed/features/search/data/models/search_videogame_response.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeSearchVideogameResponse_0 extends _i1.SmartFake
    implements _i2.SearchVideogameResponse {
  _FakeSearchVideogameResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeVideoGameWithIndivModel_1 extends _i1.SmartFake
    implements _i3.VideoGameWithIndivModel {
  _FakeVideoGameWithIndivModel_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDatabaseProvider_2 extends _i1.SmartFake
    implements _i4.DatabaseProvider {
  _FakeDatabaseProvider_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [HowLongBeatDataSource].
///
/// See the documentation for Mockito's code generation for more information.
// ignore: must_be_immutable
class MockHowLongBeatDataSource extends _i1.Mock
    implements _i5.HowLongBeatDataSource {
  MockHowLongBeatDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i6.Future<_i2.SearchVideogameResponse> searchVideoGame(
    int? pageResult,
    String? searchText,
    _i7.SearchFilterSortBy? sortBy,
    _i7.SearchFilterPlatform? platform,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #searchVideoGame,
          [
            pageResult,
            searchText,
            sortBy,
            platform,
          ],
        ),
        returnValue: _i6.Future<_i2.SearchVideogameResponse>.value(
            _FakeSearchVideogameResponse_0(
          this,
          Invocation.method(
            #searchVideoGame,
            [
              pageResult,
              searchText,
              sortBy,
              platform,
            ],
          ),
        )),
      ) as _i6.Future<_i2.SearchVideogameResponse>);
  @override
  _i6.Future<_i3.VideoGameWithIndivModel> getVideoGameDetails(int? remoteId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getVideoGameDetails,
          [remoteId],
        ),
        returnValue: _i6.Future<_i3.VideoGameWithIndivModel>.value(
            _FakeVideoGameWithIndivModel_1(
          this,
          Invocation.method(
            #getVideoGameDetails,
            [remoteId],
          ),
        )),
      ) as _i6.Future<_i3.VideoGameWithIndivModel>);
}

/// A class which mocks [VideoGameLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockVideoGameLocalDataSource extends _i1.Mock
    implements _i8.VideoGameLocalDataSource {
  MockVideoGameLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.DatabaseProvider get databaseProvider => (super.noSuchMethod(
        Invocation.getter(#databaseProvider),
        returnValue: _FakeDatabaseProvider_2(
          this,
          Invocation.getter(#databaseProvider),
        ),
      ) as _i4.DatabaseProvider);
  @override
  _i6.Future<List<_i9.VideoGameDb>> getAllVideoGames() => (super.noSuchMethod(
        Invocation.method(
          #getAllVideoGames,
          [],
        ),
        returnValue:
            _i6.Future<List<_i9.VideoGameDb>>.value(<_i9.VideoGameDb>[]),
      ) as _i6.Future<List<_i9.VideoGameDb>>);
  @override
  _i6.Future<void> insertVideoGame(
    int? remoteId,
    String? gameName,
    String? imageName,
    int? releaseYear,
    String? platformSelected,
    _i10.VideoGameStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #insertVideoGame,
          [
            remoteId,
            gameName,
            imageName,
            releaseYear,
            platformSelected,
            status,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  _i6.Future<void> deleteVideoGame(int? remoteId) => (super.noSuchMethod(
        Invocation.method(
          #deleteVideoGame,
          [remoteId],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
  @override
  _i6.Future<void> changeVideoGameStatus(
    int? remoteId,
    _i10.VideoGameStatus? status,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #changeVideoGameStatus,
          [
            remoteId,
            status,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}
